from pathlib import Path

path = Path('/home/ubuntu/danilo_caliro_portfolio/client/src/pages/Home.tsx')
text = path.read_text()
start = text.index('        <section className="contact-section section-pad" id="contact">')
end = text.index('</section>', start) + len('</section>')
section = '''        <section className="contact-section section-pad" id="contact"><div className="container contact-inner"><SectionLabel>05 / GET IN TOUCH</SectionLabel><h2>Let&apos;s turn ideas<br /><em>into images.</em></h2><p>For production, technical direction, workflow development or tools.</p>{formSent ? <div className="form-success"><Check size={18} /> Thanks — your message has been sent.</div> : <form className="contact-form" action={contactFormEndpoint} method="POST" noValidate onSubmit={async (event) => { event.preventDefault(); const form = event.currentTarget; setFormError(""); if (!form.checkValidity()) { setFormError("Please complete all required fields with a valid email address."); return; } setFormSending(true); try { const response = await fetch(contactFormEndpoint, { method: "POST", body: new FormData(form), headers: { Accept: "application/json" } }); const result = await response.json().catch(() => ({})); if (!response.ok) throw new Error(result?.errors?.[0]?.message || "Form submission failed"); setFormSent(true); } catch (error) { setFormError(error instanceof Error ? error.message : "Something went wrong. Please try again in a moment."); } finally { setFormSending(false); } }}><input className="form-honey" type="checkbox" name="_gotcha" tabIndex={-1} autoComplete="off" /><input type="hidden" name="_subject" value="New message from Danilo Caliro Portfolio" /><div className="form-row"><label><span>Your name</span><input type="text" name="name" placeholder="Name" required /></label><label><span>Email</span><input type="email" name="email" placeholder="you@example.com" required /></label></div><label><span>Message</span><textarea name="message" placeholder="Tell me about the project..." rows={4} required /></label>{formError && <p className="form-error" role="alert">{formError}</p>}<button className="button button-dark" type="submit" disabled={formSending}>{formSending ? "Sending…" : "Send message"} {!formSending && <ArrowUpRight size={17} />}</button><small>Your message will be sent securely through Formspree.</small></form>}</div></section>'''
path.write_text(text[:start] + section + text[end:])
print('Replaced contact section cleanly')
